[phases.setup]
nixPkgs = ['nodejs_20']

[phases.build]
cmds = ['npm ci', 'npm run build']

[phases.deploy]
cmd = 'npx serve dist -l 8080'

[variables]
VITE_API_BASE_URL = 'https://pos-staging.ayendecx.com/api/v1'
